### ISSUE TITLE
Server Crash After Loading Spawn Area

### ISSUE THREAD

**Issue by anthonydvives** [XCompWiz/Mystcraft-Issues#300]
Hello,

I am currently wanting to run the Mystcraft mod on my Plugin Sponge Server but I am having issues with the server crashing prompting after loading the spawn area. I am currently running:
    - spongeforge-1.12.2-2705-7.1.0-BETA-3361
    - forge-1.12.2-14.23.4.2705
The server will function fine if I remove the sponge forge mod and it appears that Mystcraft does not want to play well with Sponge Forge. I have attached the crash report that I would receive when running the issue occurs. I have brought up the issue on the Mystcraft discord server and was directed here. If needed I can also provide the full list of mods that are being used in conjunction with Mystcraft.
[crash-2018-07-31_22.39.38-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/2251275/crash-2018-07-31_22.39.38-server.txt)

**Comment by nickkeane** [comment]
Having the same issue & exception.
- mystcraft-1.12.2-0.13.6.00 (Same issue w/ 5.01)
- spongeforge-1.12.2-2705-7.1.0-BETA-3206
- forge-1.12.2-14.23.4.2715

Seems to occur immediately after:
[Mystcraft]: Baseline Profiling provider registered at -2147483648
[Mystcraft]: Baseline Profiling dimension registered at -2147483648
[Mystcraft]: Baseline Profiling for Instability started. Expect some lag.
[Sponge]: Loading world [DIM_MYST-2147483648] (Mystcraft_ProfilerDummy)

Looks like in my Exception this happens when ChunkProviderServerDummy in com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy is being constructed and set as a ChunkProviderServer for the profiler. Is this a dimension that's not meant to be created or loaded? Or is it missing some data that might be necessary for loading? In any case, SpongeForge seems to be loading it in off of some event in PostInit processing.

**Comment by Aaron1011** [comment]
This should be fixed on the latest SpongeForge

**Comment by nickkeane** [comment]
Updated to 3383 on All The Mods 3. Server loads everything.

Then, it prints a lot of this line (though it still seems to be working) for about 5 mins or so:
```
[Server thread/ERROR] [forestry]: tried to generate a hive in an unloaded area.
```

Then, it crashes with this Exception:
```
java.lang.NullPointerException: null
at org.spongepowered.common.world.WorldManager.getDimensionId(WorldManager.java:1258) ~[WorldManager.class:1.12.2-2705-7.1.0-BETA-3383]
at net.minecraft.server.MinecraftServer.redirect$onGetWorldProviderForSnooper$zjj000(MinecraftServer.java:3831) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_70000_a(MinecraftServer.java:1104) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_70000_a(DedicatedServer.java:414) ~[nz.class:?]
at net.minecraft.profiler.Snooper.func_76471_b(SourceFile:111) ~[ul.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:707) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by anthonydvives** [comment]
I updated to the latest version of Sponge Forge and still have the same issue. I attached the new crash log also. 

[crash-2018-08-10_19.45.10-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/2279735/crash-2018-08-10_19.45.10-server.txt)

Versions being used: 
- spongeforge-1.12.2-2705-7.1.0-BETA-3392
- forge-1.12.2-14.23.4.2705

**Comment by Aaron1011** [comment]
Can you open an issue on the SpongeForge issue tracker?

**Comment by nickkeane** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2373 seems to reference my issue w/ Forestry & Mystcraft. Same "tried to generate hive" message and identical Exception stack, occurring minutes later. So a fix to that will probably fix me.

Haven't seen anthony's exception above while testing. Reading it looks like when sponge is generating a chunk, it doesn't have the proper biome settings? Maybe the dummy world/dimension doesn't have default biome settings or something. Try 3383 and see if you're getting the same thing I am, Anthony. Could be your newer version of SF has an extra issue causing that Exception, idk.
