### ISSUE TITLE
Client Crash While Loading

### ISSUE THREAD

**Issue by Lewimaron** [XCompWiz/Mystcraft-Issues#318]
I've been getting the attached crash when loading the latest version of Mystcraft. The previous version works fine.

mystcraft-1.12.2-0.13.7.00 + Forge 14.23.5.2768

[crash-2018-10-19_22.19.38-client.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/2498149/crash-2018-10-19_22.19.38-client.txt)

**Comment by Veovis-Muaddib** [comment]
Sorry, looks like it's not giving a message that it needs a new Forge version.

Can you try updating to Forge 2770 or higher?

**Comment by Lewimaron** [comment]
Yep, it's working now.

**Comment by Veovis-Muaddib** [comment]
Great, thanks for confirming!

XCW: Can you please check the various manifests and annotations and bump up Forge where ever it exists for next release?

**Comment by Aldurnamiyanrandvora** [comment]
Hi, I just decided to add on to this thread since I had the same problem with the latest version. I don't know if this is because of not having the latest addition of Forge though (normally my game warns me I need to update). 

[crash-2018-10-21_15.45.48-client.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/2498760/crash-2018-10-21_15.45.48-client.txt)

**Comment by Veovis-Muaddib** [comment]
Can you try updating to Forge 2770 or higher?

**Comment by ghost** [comment]
Just chiming in that I keep running into this, the newest version that works with Forge 2768 (Recommended) is Mystcraft ~13.6.00.

Recommendations:
1-Make sure mystcraft is calling for the appropriate forge version for a given version of itself, so it presents an informative message on startup instead of crashing.
2-Build mods on a recommended version of forge, as this is what most packs will be built on.

**Comment by Aldurnamiyanrandvora** [comment]
Hi, sorry I only just got back, it does indeed work on the newer version of Forge. I've been a bit hesitant of updating because of I always use Thaumcraft in my mod pack, and it's been inconsistent with the newer versions of Forge, but that's Thaumcraft's problem, not Mystcraft's.

**Comment by Pythonic-Rainbow** [comment]
Thaumcraft issue is fixed quite a while ago.

**Comment by 7larson** [comment]
I'm getting this exact same error and I've tried changing to every Forge version from 2770 up and it's still happening. Any further advice?

EDIT: I went back and tried again. It didn't work with 2770, 2774, or 2775, but I got it working with 2771? But now of course Thaumcraft is causing the same crash. Oof. Well, I tried!

**Comment by HellFirePvP** [comment]
Mystcraft will ask for a more recent forge version on startup now so using the current recommended or a more recent build is - well - recommended.
